# Generated by Django 2.2.5 on 2020-03-07 23:36

from django.db import migrations
import djongo.models.fields
import evaluators.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('players', djongo.models.fields.ArrayModelField(model_container=evaluators.models.PlayerById)),
                ('turn_player_scores', djongo.models.fields.ArrayModelField(model_container=evaluators.models.PlayerScore)),
                ('flop_player_scores', djongo.models.fields.ArrayModelField(model_container=evaluators.models.PlayerScore)),
                ('river_player_scores', djongo.models.fields.ArrayModelField(model_container=evaluators.models.PlayerScore)),
                ('board', djongo.models.fields.EmbeddedModelField(model_container=evaluators.models.Board, null=True)),
            ],
        ),
    ]
