# Generated by Django 2.2.5 on 2020-01-04 18:13

import django.contrib.postgres.fields
from django.db import migrations, models
import djongo.models.fields
import evaluators.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flop', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=3)),
                ('turn', models.CharField(max_length=2)),
                ('river', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('players', djongo.models.fields.ArrayModelField(model_container=evaluators.models.PlayerById)),
                ('board', djongo.models.fields.EmbeddedModelField(model_container=evaluators.models.Board, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerById',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', djongo.models.fields.EmbeddedModelField(model_container=evaluators.models.Player, null=True)),
                ('hand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=2)),
            ],
        ),
    ]
