# Generated by Django 2.2.5 on 2020-01-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0002_auto_20200104_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='name',
            field=models.CharField(default='NAME', max_length=100),
            preserve_default=False,
        ),
    ]
