# Generated by Django 2.2.5 on 2020-01-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0003_hand_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerById',
        ),
        migrations.AlterField(
            model_name='hand',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
