# Legacy! Generated by Django 2.2.5 on 2020-01-04 18:16

from django.db import migrations
import uuid
from evaluators.game import shuffle, gen_next_index

def create_static_hands(apps, schema_editor):
    Board = apps.get_model('evaluators', 'Board')
    Hand = apps.get_model('evaluators', 'Hand')
    Player = apps.get_model('evaluators', 'Player')
    PlayerById = apps.get_model('evaluators', 'PlayerById')
    negs = Player(uuid=uuid.uuid4(), name="Danieal Negraunu")
    ivy = Player(uuid=uuid.uuid4(), name="Phil Ivey")
    ant = Player(uuid=uuid.uuid4(), name="Patrick Antonius")
    helm = Player(uuid=uuid.uuid4(), name="Phil Helmuth")
    #negs.save()
    #ivy.save()
    #ant.save()
    #helm.save()
    players = [negs, ivy, ant, helm]
    cards = shuffle()
    players_by_id = []
    nextn = gen_next_index()
    i = 0
    pl = len(players)
    for p in players:
        i = next(nextn)
        player_hand = hand=[cards[i],cards[i+len(players)]]
        pbi = PlayerById(player=p, hand=player_hand)
        players_by_id.append(pbi)
    flop=[cards[next(nextn)+pl], cards[next(nextn)+pl], cards[next(nextn)+pl]]
    turn=cards[next(nextn)+pl]
    river=cards[next(nextn)+pl]
    board = Board(flop=flop, turn=turn, river=river)
    #board = Board(flop=[cards[next(nextn)+pl], cards[next(nextn)+pl]],turn=cards[next(nextn)+pl], river=cards[next(nextn)+pl])
    hand = Hand(players=players_by_id, board=board)
    hand.save()

class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_static_hands),
    ]
